# Generated by Django 2.1.5 on 2019-03-12 05:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, upload_to='files')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
            ],
        ),
    ]
