# Generated by Django 2.1.5 on 2019-03-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writer',
            new_name='User',
        ),
    ]
