# Generated by Django 2.1.5 on 2019-03-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190312_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
