# Generated by Django 2.1.5 on 2019-03-30 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190312_1603'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relpy',
            name='article',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
            preserve_default=False,
        ),
    ]
