# Generated by Django 2.1.5 on 2019-03-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_relpy_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relpy',
            name='reply_id',
        ),
    ]
