# Generated by Django 2.1.5 on 2019-03-31 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190330_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relpy',
            name='article',
        ),
        migrations.AlterField(
            model_name='relpy',
            name='reply_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment'),
        ),
    ]
